export const INIT_FORECAST = 'INIT_FORECAST'
export const UPDATE_FORECAST = 'UPDATE_FORECAST'

export const INIT_POSITION = 'INIT_POSITION'
export const UPDATE_POSITION = 'UPDATE_POSITION'

export const START_AUTIFACATION = 'START_AUTIFACATION'
export const UPLOAD_EVENT = 'UPLOAD_EVENT'
export const QUIT_FROM_CALENDAR = 'QUIT_FROM_CALENDAR'
export const CLEAR_EVENT = 'CLEAR_EVENT'
